name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{segrets.DOCKER_USERNAME}/daniele:latest

    - name : Docker login
      run: docker login -u ${{segrets.DOCKER_USERNAME}} --password-stdin ${{segrets.DOCKER_TOKEN}

    - name : Push Image to DockerHub
      run: docker push -t ${{segrets.DOCKER_USERNAME}}daniele:latest

      

      
    
